# Generated by Django 3.2.4 on 2023-09-19 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0003_alter_sound_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flag', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='sounds.sound')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
