# Generated by Django 3.2.4 on 2023-09-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='flag',
            field=models.CharField(choices=[('hate', 'Hate speech'), ('illegal', 'Illegal/extremist content'), ('violence', 'Violent content'), ('pornographic', 'Pornographic Content'), ('harassment', 'Harassment or bullying'), ('privacy', 'Privacy violation'), ('property', 'Intellectual property violation'), ('other', 'Other')], max_length=50),
        ),
    ]
