# Generated by Django 3.2.4 on 2023-09-19 10:21

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_auto_20230916_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=15, to='sounds.Tagulous_Sound_tags'),
        ),
    ]
