# Generated by Django 3.2.4 on 2023-09-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('follow', 'Follow'), ('comment', 'Comment'), ('like', 'Like'), ('new_sound', 'New Sound'), ('report', 'Report')], max_length=50),
        ),
    ]
